### ISSUE TITLE
[Feature request] Ideas for future developement

### ISSUE THREAD

**Issue by CGrassin** [dernasherbrezon/rtlSpectrum#6]
I have been using rtlSpectrum for radio astronomy, as a quick and easy way to view files before the actual post processing. Having a simple GUI to view `rtl_power` files is a great idea!
It works great, but here are some ideas for future features, if you take requests:
* Rescale/zoom on the frequency axis: most of my scans are only on a small part of the frequency range of the SDR,
* Rescale/zoom on the power axis,
* A GUI window for selecting scan parameters: instead of running the command directly with fixed parameters, it would be great to be able to tweak frequency, gain, crop and integration time,
* No smoothing: I may be mistaken, but it seems like the graph is smoothed. It would be nice to have an option to view raw data (i.e. straight lines instead of smoothed lines),
* It should be "Hz" instead of "hz" on the frequency axis,
* Some way to change colors ?
* Files with multiple scans are not handled properly. They should probably be averaged over time (see picture below).
* Maybe give the option to display power vs time instead of power vs frequency: this is useful for radio astronomy because I often do narrow band work over an extended duration (hours) to look at variations over time.

![Screenshot from 2020-08-24 09-42-36](https://user-images.githubusercontent.com/42406777/91017300-59cff700-e5ee-11ea-987a-9b5378b6f1e0.png)

**Comment by dernasherbrezon** [comment]
Hey,

Looks very impressive list of features :) 

Most of them valid. What about files with multiple scans? Can you attach it here?

> Maybe give the option to display power vs time instead of power vs frequency

This would be too disconnected with the whole rtlSpectrum idea - i.e. simple tool for rendering rtl_power output. You might try different tool - https://github.com/miek/inspectrum . It can support rendering power over frequency / time. So instead of using "rtl_power" you can use "rtl_sdr", take i/q data swipes and write to file. This is essentially what rtl_power is doing.

**Comment by dernasherbrezon** [comment]
Fixed the bug. Raised separate issue to support waterfalls #7
